api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "fulfillment-constraints"
type = "function"
uid = "503224a7-8d2c-4bbc-ace0-602251d510aa"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.fulfillment-constraints.generate.run"
  input_query = "src/cart_fulfillment_constraints_generate_run.graphql"
  export = "cart-fulfillment-constraints-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
